development:
  cloud_name: "dyf68ygvd"
  api_key: <%= Rails.application.credentials.cloudinary.fetch(:api_key) %>
  api_secret: <%= Rails.application.credentials.cloudinary.fetch(:api_secret) %>
  secure: true

production:
  cloud_name: "dyf68ygvd"
  api_key: <%= Rails.application.credentials.cloudinary.fetch(:api_key) %>
  api_secret: <%= Rails.application.credentials.cloudinary.fetch(:api_secret) %>
  secure: true
